# Generated by Django 5.1.6 on 2025-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_category_rename_added_at_favorite_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Dessert', 'Dessert'), ('Vegan', 'Vegan'), ('Halal', 'Halal')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, choices=[('Vegetarian', 'Vegetarian'), ('Dinner', 'Dinner'), ('Lunch', 'Lunch'), ('Snack', 'Snack'), ('Dessert', 'Dessert'), ('Vegan', 'Vegan'), ('Halal', 'Halal')], max_length=100, null=True),
        ),
    ]
